# ../docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./react_template
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./react_template:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]